### ISSUE TITLE
Move the namespace definition to the head of the turtle file

### ISSUE THREAD

**Issue by edgardmarx** [AKSW/life-knowledge-base#4]
wrong

```
ns1:5T6MX	ns0:taxonomicStatus	"accepted" .
@prefix ns2:	<http://www.w3.org/2000/01/rdf-schema#> .
ns1:5T6MX	ns2:label	"5T6MX" .
@prefix ns3:	<http://ontology.col.htwk-leipzig.de/> .
ns1:5T6MX	ns0:taxonRank	ns3:Unranked ;
	a	ns3:Unranked ;
	ns0:nomenclaturalStatus	"nomen legitimum" ;
	ns0:scientificName	"Biota" ;
```

right

```
@prefix ns2:	<http://www.w3.org/2000/01/rdf-schema#> .
@prefix ns3:	<http://ontology.col.htwk-leipzig.de/> .
ns1:5T6MX	ns0:taxonomicStatus	"accepted" .
ns1:5T6MX	ns2:label	"5T6MX" .
ns1:5T6MX	ns0:taxonRank	ns3:Unranked ;
	a	ns3:Unranked ;
	ns0:nomenclaturalStatus	"nomen legitimum" ;
	ns0:scientificName	"Biota" ;
```

**Comment by JLXE5** [comment]
It does not seem to be required by the standard: https://www.w3.org/TR/turtle.

I understand why it is desirable to have all the prefixes at the beginning of the document. 
Unfortunately this behavior is not serializable, which is why the library I used for turning the document into ttl-format decided against it. 

I could imagine the best way to still have the prefixes first would be to do post-processing using 2 bash pipes. 
Would you like to do it this way?

**Comment by JLXE5** [comment]
It does not seem to be required by the standard: https://www.w3.org/TR/turtle.

I understand why it is desirable to have all the prefixes at the beginning of the document. 
Unfortunately this behavior is not serializable, which is why the library I used for turning the document into ttl-format decided against it. 

I could imagine the best way to still have the prefixes first would be to do post-processing using 2 bash pipes. 
Would you like to do it this way?

**Comment by edgardmarx** [comment]
sure

**Comment by JLXE5** [comment]
closing since data is not parsed to ttl any more
